// Package animal provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.1-0.20220812203637-fec990c8f823 DO NOT EDIT.
package animal

// PostAnimalRequestValidationJSONBody defines parameters for PostAnimalRequestValidation.
type PostAnimalRequestValidationJSONBody struct {
	Name    *string `json:"name,omitempty"`
	Species *string `json:"species,omitempty"`
}

// PostAnimalRequestValidationJSONRequestBody defines body for PostAnimalRequestValidation for application/json ContentType.
type PostAnimalRequestValidationJSONRequestBody PostAnimalRequestValidationJSONBody
